name: build and publish

on:
  push:
    branches: ['master']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push docker image
        run: |
          docker build . --tag "${REGISTRY}/${GITHUB_REPOSITORY}:${VERSION}"

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: |
          docker push "${REGISTRY}/${GITHUB_REPOSITORY}:${VERSION}"
